---
title: "A.barbata MMRR"
author: "Andrés Delgado Galán"
date: "2026-02-10"
output: html_document
---

```{r LOADING DATA AND PACKAGES, include=FALSE}
# --- Core packages ---
library(here)        # Reproducibilidad de rutas
library(tidyverse)   # Incluye ggplot2, dplyr, tidyr, readr, purrr, stringr, forcats, tibble
library(cluster)     # Matriz de disimilaridad con método gower

# --- Estadística ---
library(vegan)       # Mantel test


# --- Visualización y clustering ---


# --- Genética ---
library(vcfR)        # read and manipulate VCF files
library(adegenet)

# --- SMPs ---
avena_CpG_obj <- readRDS(here("avena_ncbi", "avena_ncbi_CpG_meth_matrix.rds"))
avena_CHG_obj <- readRDS(here("avena_ncbi", "avena_ncbi_CHG_meth_matrix.rds"))
avena_CHH_obj <- readRDS(here("avena_ncbi", "avena_ncbi_CHH_meth_matrix.rds"))
# plantago_CpG_obj <- readRDS(here("plantago_pseudo", "plantago_pseudo_CpG_meth_matrix.rds"))
# plantago_CHG_obj <- readRDS(here("plantago_pseudo", "plantago_pseudo_CHG_meth_matrix.rds"))
# plantago_CHH_obj <- readRDS(here("plantago_pseudo", "plantago_pseudo_CHH_meth_matrix.rds"))

# --- TRATAMIENTOS ---
treatment_table <- read.table(file = here("avena_treatment.csv"), header = T, sep = ";")
          # Quitamos las muestras que no vamos a usar (sin tratar o inexistentes)
          treatment_table <- treatment_table %>%
            filter(!id %in% c(
              "AV253_2", "AV243_2", "AV282_2",
              "AV280_2", "AV297_2", "AV275", "AV296_2"
            ))

# --- SNPs ---
vcf <- read.vcfR(here("avena_ncbi", "filtered_variants_cov5-1000_biallelic_MAF0.01_80pct.vcf.gz"))

# --- FENOTIPO ---
phenotype_table <- read.table(file = here("datos_sibecol_2025.csv"), header = T, sep = ";")
          # Añadimos los datos de WINRHIZO
          winrhizo <- read.table(here("winrhizo.csv"), header = T, sep = ",")
          raices_pesos_gabi <- read.table(here("raices_pesos_gabi.csv"), header = T, sep = ",")
          raices_pesos_lore <- read.table(here("raices_pesos.csv"), header = T, sep = ",")
          raices_pesos <- full_join(raices_pesos_gabi, raices_pesos_lore, by = "id")
          
          # discrepancias entre las dos bases de datos
          reporte_discrepancias <- raices_pesos %>%
  # Creamos una columna que concatena los nombres de las variables que fallan
  mutate(
    discrepancia = paste0(
      if_else(sp.x != sp.y, "sp, ", ""),
      if_else(profundidad_sustrato.x != profundidad_sustrato.y, "profundidad, ", ""),
      if_else(peso_resto.x != peso_resto.y, "peso_resto, ", ""),
      # Usamos coalesce para que los NA no rompan la comparación
      if_else(coalesce(peso_winrhizo.x != peso_winrhizo.y, TRUE), "peso_winrhizo, ", "")
    ),
    # Limpiamos la coma final de la cadena de texto
    discrepancia = gsub(", $", "", discrepancia)
  ) %>%
  # Filtramos: solo filas donde la columna discrepancia NO esté vacía
  filter(discrepancia != "") %>%
  # Reorganizamos para ver la causa primero
  select(id, discrepancia, everything())
          
          
          reporte_limpio <- raices_pesos %>%
  mutate(
    discrepancia = paste0(
      # Comparamos solo si AMBOS no son NA Y son distintos
      if_else(!is.na(sp.x) & !is.na(sp.y) & sp.x != sp.y, "sp, ", ""),
      
      if_else(!is.na(profundidad_sustrato.x) & !is.na(profundidad_sustrato.y) & 
                profundidad_sustrato.x != profundidad_sustrato.y, "profundidad, ", ""),
      
      if_else(!is.na(peso_resto.x) & !is.na(peso_resto.y) & 
                peso_resto.x != peso_resto.y, "peso_resto, ", ""),
      
      if_else(!is.na(peso_winrhizo.x) & !is.na(peso_winrhizo.y) & 
                peso_winrhizo.x != peso_winrhizo.y, "peso_winrhizo, ", "")
    ),
    # Limpiar la coma y espacio final
    discrepancia = gsub(", $", "", discrepancia)
  ) %>%
  # Nos quedamos solo con las filas que tienen texto en 'discrepancia'
  filter(discrepancia != "") %>%
  select(id, discrepancia, everything())
          
          
          # NOS QUEDAMOS CON LOS DATOS DE GABI QUE ESTÁN COMPLETOS
          
          
          
          # Nos quedamos con las variables que nos interesan y las muestras que estamos analizando 
          winrhizo_selection <- winrhizo%>%
            select(c(RHIZO.2009, AvgDiam.mm., Length.cm., RootVolume.cm3.))%>%
            filter(RHIZO.2009 %in% treatment_table$id)%>%
            rename(full_id = RHIZO.2009)
          
          # Nos quedamos con las muestras que estamos analizando 
          raices_selection <- raices_pesos_gabi %>%
            mutate(full_id = paste0(sp, id)) %>%
            filter(full_id %in% treatment_table$id)

          # Unimos todos los datos de raíces
          winrhizo_full <- 
            full_join(winrhizo_selection, raices_selection,by = "full_id")%>%
            mutate(RTD = paste0(peso_winrhizo/RootVolume.cm3.))%>%
            mutate(SRL = paste0(Length.cm./peso_winrhizo))
            
          # Eliminamos variables que no vamos a usar y nos quedamos con nuestras muestras
          phenotype_selection <- phenotype_table %>%
            select(-c(massmother, seedfruto, humedad_muerte, dias_muerte, dias_fin_flor, dias_fin_fruto))
          
          
           
                    # Construimos la matriz de nuestras muestras sin metadatos
          phenotype_selection <- phenotype_table %>%
            select(-c(massmother, seedfruto, humedad_muerte, dias_muerte, dias_fin_flor, dias_fin_fruto)) %>%
            mutate(full_id = paste0(sp, id)) %>%
            filter(full_id %in% treatment_table$id) %>%
            select(-id, -sp, -trat, -clip)
          
          # Unimos fenotipo con raíces
          # 1. Crear el dataframe procesado primero
          phenotype_df <- full_join(phenotype_selection, winrhizo_full, by = "full_id") %>%
            column_to_rownames("full_id") %>%
            select(-c(peso_winrhizo, peso_resto, Length.cm., RootVolume.cm3., id, sp, profundidad_sustrato))
          
          # 2. Convertir a matriz
          phenotype_matrix <- as.matrix(phenotype_df)
          
          # 3. Forzar el tipo numérico preservando los nombres
          class(phenotype_matrix) <- "numeric"
          
          # 4. Verificar
          head(phenotype_matrix)

```

```{r EPIGENETIC distance MATRIX, include=FALSE}
#Transpose methylation matrix (individuals have to be rows)
CpG_meth_matrix <- t(avena_CpG_obj)

# Distancia euclídea
CpG_dist_matrix <- 
  dist(CpG_meth_matrix, method = "euclidean")


E <- as.matrix(CpG_dist_matrix)
heatmap(E, symm = TRUE)
hc <- hclust(CpG_dist_matrix)
plot(hc)
heatmap(E, Rowv = as.dendrogram(hc), Colv = as.dendrogram(hc), symm = TRUE)

```

```{r SNP distance matrix, include=FALSE}
# Convert to genlight (handles large SNP sets efficiently)
gl <- vcfR2genlight(vcf)    # converts to genlight; ploidy defaults to 2
indNames(gl) <- sub("_R1_trimmed_bismark_bt2_pe\\.sorted$", "", indNames(gl))


# compute allele dosage matrix
dos <- as.matrix(gl)  # genlight -> numeric matrix (0/1/2), NAs remain
# Remove some monomorphic positions
keep <- apply(dos, 2, function(x) {
    u <- unique(na.omit(x))
    length(u) > 1
})
sum(!keep)    # should show 79
dos_filtered <- dos[, keep]

# Distancia genética
SNP_dist_matrix <- 
  dist(dos, method = "euclidean")

G <- as.matrix(SNP_dist_matrix)
heatmap(G, symm = TRUE)
hc <- hclust(SNP_dist_matrix)
plot(hc)
heatmap(G, Rowv = as.dendrogram(hc), Colv = as.dendrogram(hc), symm = TRUE)

```

```{r PHENOTYPE distance matrix, include=FALSE}
# Escalar rasgos fenotípicos
phenotype_scaled <- scale(phenotype_matrix, center = TRUE, scale = TRUE)

# Distancia fenotípica
PHENOTYPE_dist_matrix <- 
  dist(phenotype_scaled, method = "euclidean")

P <- as.matrix(PHENOTYPE_dist_matrix)
heatmap(P, symm = TRUE)
hc <- hclust(PHENOTYPE_dist_matrix)
plot(hc)
heatmap(P, Rowv = as.dendrogram(hc), Colv = as.dendrogram(hc), symm = TRUE)

```

```{r ENVIRONMENTAL distance matrix, include=FALSE}
# Poner id como rownames en treatment
rownames(treatment_table) <- treatment_table$id

# Convertir a factor
treatment_table$maternal   <- as.factor(treatment_table$maternal)
treatment_table$simulation <- as.factor(treatment_table$simulation)

# Crear dataframe solo con factores
env_data <- treatment_table[, c("maternal", "simulation")]

# Distancia Gower
ENV_dist_matrix <- 
  daisy(env_data, metric = "gower")

ENV <- as.matrix(ENV_dist_matrix)
heatmap(ENV, symm = TRUE)
hc <- hclust(ENV_dist_matrix)
plot(hc)
heatmap(ENV, Rowv = as.dendrogram(hc), Colv = as.dendrogram(hc), symm = TRUE)

```


```{r preparando matrices para MMRR, include=FALSE}
# daisy() devuelve un objeto clase "dissimilarity"
# MMRR trabaja con objetos tipo matrix
# Convertimos las matrices
CpG_dist_matrix <- as.matrix(CpG_dist_matrix)
SNP_dist_matrix <- as.matrix(SNP_dist_matrix)
PHENOTYPE_dist_matrix <- as.matrix(PHENOTYPE_dist_matrix)
ENV_dist_matrix <- as.matrix(ENV_dist_matrix)

# Estandarizamos las matrices: mean=0;SD=1
# Creamos una función
standardize_matrix <- function(mat){
  
  vals <- mat[lower.tri(mat)]
  m <- mean(vals, na.rm = TRUE)
  s <- sd(vals, na.rm = TRUE)
  
  mat_std <- mat
  mat_std[lower.tri(mat_std)] <- (vals - m) / s
  mat_std[upper.tri(mat_std)] <- t(mat_std)[upper.tri(mat_std)]
  diag(mat_std) <- 0
  
  return(mat_std)
}



# Aplicamos la función
CpG_dist_matrix_std  <- standardize_matrix(CpG_dist_matrix)
SNP_dist_matrix_std  <- standardize_matrix(SNP_dist_matrix)
PHENO_dist_matrix_std <- standardize_matrix(PHENOTYPE_dist_matrix)
ENV_dist_matrix_std  <- standardize_matrix(ENV_dist_matrix)

# Comprobamos que la media es 0 y la desviación estándar es 1
mean(CpG_dist_matrix_std[lower.tri(CpG_dist_matrix_std)])
sd(CpG_dist_matrix_std[lower.tri(CpG_dist_matrix_std)])
mean(SNP_dist_matrix_std[lower.tri(SNP_dist_matrix_std)])
sd(SNP_dist_matrix_std[lower.tri(SNP_dist_matrix_std)])
mean(PHENO_dist_matrix_std[lower.tri(PHENO_dist_matrix_std)])
sd(PHENO_dist_matrix_std[lower.tri(PHENO_dist_matrix_std)])
mean(ENV_dist_matrix_std[lower.tri(ENV_dist_matrix_std)])
sd(ENV_dist_matrix_std[lower.tri(ENV_dist_matrix_std)])

# Todas las matrices deben tener el mismo orden de muestras
# Si alguna línea devuelve FALSE, hay que reordenar la matriz
identical(rownames(PHENO_dist_matrix_std), rownames(SNP_dist_matrix_std))
identical(rownames(PHENO_dist_matrix_std), rownames(CpG_dist_matrix_std))
identical(rownames(PHENO_dist_matrix_std), rownames(ENV_dist_matrix_std))

# Si alguna no coincide:
# Reordenar filas y columnas de ENV para que coincidan con PHENO
ENV_dist_matrix_std <- ENV_dist_matrix_std[rownames(PHENO_dist_matrix_std), colnames(PHENO_dist_matrix_std)]

# Verificación
identical(rownames(PHENO_dist_matrix_std), rownames(ENV_dist_matrix_std))

# Testamos multicolinealidad
# Si alguna correlación > 0.7–0.8, interpretamos los betas del MMRR con cuidado.
cor(SNP_dist_matrix_std[lower.tri(SNP_dist_matrix_std)],
    CpG_dist_matrix_std[lower.tri(CpG_dist_matrix_std)])   # CUIDADO!

cor(SNP_dist_matrix_std[lower.tri(SNP_dist_matrix_std)],
    ENV_dist_matrix_std[lower.tri(ENV_dist_matrix_std)])

cor(CpG_dist_matrix_std[lower.tri(CpG_dist_matrix_std)],
    ENV_dist_matrix_std[lower.tri(ENV_dist_matrix_std)])


```

```{r MANTEL OPCIONAL, include=FALSE}
# Esto lo hacen en Monguer22 pero en nuestro caso no sé si tendría más sentido incluirlo en el dbRDA
# mantel(PHENOTYPE_dist_matrix,
#        ENV_dist_matrix,
#        method = "pearson",
#        permutations = 9999)
```

```{r MMRR, include=FALSE}
# MMRR performs Multiple Matrix Regression with Randomization analysis
# Y is a dependent distance matrix
# X is a list of independent distance matrices (with optional names)
# Función para el modelo
MMRR <- function(Y, X, nperm = 999){
  
  Y <- as.matrix(Y)
  X <- lapply(X, as.matrix)
  
  # Extraer triángulo inferior
  y <- Y[lower.tri(Y)]
  Xs <- do.call(cbind, lapply(X, function(x) x[lower.tri(x)]))
  
  if(is.null(colnames(Xs))){
    colnames(Xs) <- paste0("X", 1:ncol(Xs))
  }
  
  # Modelo observado
  fit <- lm(y ~ Xs)
  summ <- summary(fit)
  
  coef_obs <- coef(fit)
  t_obs <- summ$coefficients[, "t value"]
  r2_obs <- summ$r.squared
  F_obs <- summ$fstatistic[1]
  
  # Almacenar permutaciones
  perm_coefs <- matrix(NA, nperm, length(coef_obs))
  perm_t <- matrix(NA, nperm, length(coef_obs))
  perm_r2 <- numeric(nperm)
  perm_F <- numeric(nperm)
  
  n <- nrow(Y)
  
  for(i in 1:nperm){
    
    perm_idx <- sample(1:n)
    Y_perm <- Y[perm_idx, perm_idx]
    y_perm <- Y_perm[lower.tri(Y_perm)]
    
    fit_perm <- lm(y_perm ~ Xs)
    summ_perm <- summary(fit_perm)
    
    perm_coefs[i, ] <- coef(fit_perm)
    perm_t[i, ] <- summ_perm$coefficients[, "t value"]
    perm_r2[i] <- summ_perm$r.squared
    perm_F[i] <- summ_perm$fstatistic[1]
  }
  
  # p-values con corrección +1
  p_coef <- sapply(1:length(coef_obs), function(i)
    (sum(abs(perm_t[, i]) >= abs(t_obs[i])) + 1) / (nperm + 1)
  )
  
  p_F <- (sum(perm_F >= F_obs) + 1) / (nperm + 1)
  p_r2 <- (sum(perm_r2 >= r2_obs) + 1) / (nperm + 1)
  
  results <- data.frame(
    Coefficient = coef_obs,
    t.value = t_obs,
    p.value = p_coef
  )
  
  list(
    R2 = r2_obs,
    R2_p = p_r2,
    F_statistic = F_obs,
    F_p = p_F,
    Coefficients = results
  )
}


# Lista de predictores
X_list <- list(
 # Genetic = SNP_dist_matrix_std,
  Epigenetic = CpG_dist_matrix_std,
  Environmental = ENV_dist_matrix_std
)

# Ejecutamos el modelo
mmrr_result <- MMRR(
  Y = PHENO_dist_matrix_std,
  X = X_list,
  nperm = 9999
)

# Resultados
mmrr_result$R2
mmrr_result$F_statistic
mmrr_result$F_p
mmrr_result$Coefficients

```

